### ISSUE TITLE
Issue on 3.3.3 to do with Jenssegers dependency

### ISSUE THREAD

**Issue by teebling** [Senky/phpbb-ext-relativedates#5]
Receiving the following fatal error:

`Fatal error: Uncaught Error: Class 'Jenssegers\Date\Date' not found in /opt/lampp/htdocs/ext/senky/relativedates/relativedatetime.php:15 Stack trace: #0 /opt/lampp/htdocs/phpbb/class_loader.php(160): require() #1 [internal function]: phpbb\class_loader->load_class('\\senky\\relative...') #2 /opt/lampp/htdocs/phpbb/user.php(681): spl_autoload_call('senky\\relatived...') #3 /opt/lampp/htdocs/ext/senky/relativedates/event/listener.php(67): phpbb\user->create_datetime(1613404416) #4 /opt/lampp/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(214): senky\relativedates\event\listener->custom_format_date(Object(phpbb\event\data), 'core.user_forma...', Object(phpbb\event\dispatcher)) #5 /opt/lampp/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'core.user_forma...', Object(phpbb\event\data)) #6 /opt/lampp/htdocs/phpbb/event/dispatcher.php(62): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('core.user_forma...', Object(phpbb in /opt/lampp/htdocs/ext/senky/relativedates/relativedatetime.php on line 15`

On phpBB 3.3.3 fresh install.

**Comment by teebling** [comment]
Fixed it! Steps:

- Dropped relativedates from the ext table in the database
- Manually purged cache (deleted all contents of cache/production folder)
- Downloaded the version from here on phpBB (NOT github master version)
- Enabled extension from the ACP
- DISABLED extension from the ACP
- DELETED DATA from the extension in ACP
- Re-enabled, works!
